--Question 1
SELECT NBRCOMMANDE, PLAT FROM (SELECT PLAT.ID AS PLAT, COUNT(COMMANDE.ID) AS NBRCOMMANDE FROM COMMANDE, CONCERNE, PLAT WHERE
    CONCERNE.COMMANDE = COMMANDE.ID
    AND CONCERNE.PLAT = PLAT.ID
        AND EXTRACT(DAY FROM HORAIRELIVRAISON - to_timestamp(CONCAT('01-01-', CONCAT(EXTRACT(YEAR FROM HORAIRELIVRAISON), ' 00:00:00')) , 'dd-mm-yyyy hh24:mi:ss')) BETWEEN 170 AND 264 GROUP BY PLAT.ID ORDER BY NBRCOMMANDE DESC) WHERE ROWNUM = 1;

--Question 2
SELECT MODEPAIEMENT, OCCURENCE FROM (SELECT FACTURE.MODEPAIEMENT AS MODEPAIEMENT, COUNT(MODEPAIEMENT) AS OCCURENCE  FROM CLIENT, PAYE, FACTURE WHERE MONTHS_BETWEEN(SYSDATE, CLIENT.DATEANNIVERSAIRE) / 12 BETWEEN 18 AND 22 AND LOWER(CLIENT.VILLE) = 'paris'
AND PAYE.CLIENT = CLIENT.ID AND FACTURE.IDTRANSACTION = PAYE.FACTURE GROUP BY MODEPAIEMENT ORDER BY OCCURENCE DESC) WHERE ROWNUM = 1;

--Question 3
SELECT VILLE, OCCURENCE FROM (SELECT COUNT(ADDRESSE.VILLE) AS OCCURENCE, ADDRESSE.VILLE AS VILLE  FROM ADDRESSE JOIN COMMANDE ON ADDRESSE.ID = COMMANDE.ADDRESSE GROUP BY ADDRESSE.VILLE ORDER BY OCCURENCE DESC)
             WHERE OCCURENCE = (SELECT MAX(OCCURENCE) FROM (SELECT COUNT(ADDRESSE.VILLE) AS OCCURENCE FROM ADDRESSE JOIN COMMANDE ON ADDRESSE.ID = COMMANDE.ADDRESSE GROUP BY ADDRESSE.VILLE));

--Question 4
SELECT RESTO, NOTEMOYENNE FROM (SELECT PLAT.RESTAURANT AS RESTO, AVG(NOTE.VALEUR) AS NOTEMOYENNE FROM PLAT JOIN NOTE ON PLAT.ID = NOTE.PLAT GROUP BY PLAT.RESTAURANT) WHERE NOTEMOYENNE =
                                (SELECT MAX(NOTEMOYENNE) FROM (SELECT AVG(NOTE.VALEUR) AS NOTEMOYENNE FROM PLAT JOIN NOTE ON PLAT.ID = NOTE.PLAT GROUP BY PLAT.RESTAURANT));

--Question 5
SELECT ROUND(AVG(AGE), 2) AS MOYENNEAGE FROM (SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, CLIENT.DATEANNIVERSAIRE) / 12) AS AGE FROM CLIENT WHERE LOWER(CLIENT.VILLE) = 'beauvais');

--Question 6
SELECT LIVREUR.NOM, COUNT(COMMANDE.ID) AS NBRCOMMANDE FROM LIVREUR JOIN COMMANDE on LIVREUR.ID = COMMANDE.LIVREUR WHERE EXTRACT( MONTH FROM HORAIRELIVRAISON) = 2 AND EXTRACT(YEAR FROM HORAIRELIVRAISON) = 2020 GROUP BY LIVREUR.NOM;

--Question 7
SELECT LIVREUR, SUM(DISTANCE) AS DISTANCEEN2020 FROM COMMANDE WHERE EXTRACT(YEAR FROM HORAIRELIVRAISON) = 2020 GROUP BY LIVREUR;

--QUESTION 8
SELECT AVG(FLOOR(MONTHS_BETWEEN(SYSDATE, DATEANNIVERSAIRE) / 12)) FROM CLIENT WHERE ID IN (SELECT PREND.CLIENT FROM PREND JOIN COMMANDE ON PREND.COMMANDE = COMMANDE.ID WHERE EXTRACT(YEAR FROM COMMANDE.HORAIRELIVRAISON) = 2021 GROUP BY PREND.CLIENT);

--Question 9
SELECT CLIENT.NOM, CLIENT.PRENOM FROM CLIENT WHERE ID = (SELECT CLIENT FROM (SELECT PREND.CLIENT AS CLIENT, COUNT(COMMANDE.ID) AS NBRCOMMANDE FROM PREND JOIN COMMANDE on PREND.COMMANDE = COMMANDE.ID  WHERE EXTRACT(YEAR FROM COMMANDE.HORAIRELIVRAISON) = 2019 GROUP BY PREND.CLIENT ORDER BY NBRCOMMANDE DESC) WHERE ROWNUM = 1);

--Question 10
SELECT CLIENT, SOMME FROM (SELECT SUM(MONTANT) AS SOMME, AVOIR.CLIENT AS CLIENT FROM AVOIR GROUP BY AVOIR.CLIENT ORDER BY SOMME DESC) WHERE ROWNUM = 1;

--Question 11
 SELECT ROUND(COUNT(PARRAINE) / SUM(NBR) * 100, 1) AS NBRPARRAINE FROM (SELECT PARRAINE, COUNT(ID) AS NBR FROM CLIENT GROUP BY PARRAINE);